spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/simplebank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Paige123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0 # 数据库索引
  #    password: dev #

logging:
  path: ./log
  level:
    org:
      springframework:
        kafka: ERROR
#        beans:
#          factory: DEBUG
#        context:
#          annotation: DEBUG
      apache:
       kafka: ERROR